### ISSUE TITLE
issue regarding gen.py

### ISSUE THREAD

**Issue by Onkarsus13** [IngleJaya95/SynthTextHindi#2]
I had installed the dependencies regarding the repo but still, i am facing an issue  in `gen.py` 
`(syntext) D:\SynthTextHindi>python gen.py
pygame 2.0.3 (SDL 2.0.16, Python 3.5.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "gen.py", line 19, in <module>
    from synthgen import *
  File "D:\SynthTextHindi\synthgen.py", line 20, in <module>
    import text_utils as tu
  File "D:\SynthTextHindi\text_utils.py", line 23, in <module>
    import qahirah as qah
  File "D:\Anaconda\envs\syntext\lib\site-packages\qahirah.py", line 42, in <module>
    import freetype2
  File "D:\Anaconda\envs\syntext\lib\site-packages\freetype2.py", line 47, in <module>
    ft = ct.cdll.LoadLibrary("libfreetype.so.6")
  File "D:\Anaconda\envs\syntext\lib\ctypes\__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "D:\Anaconda\envs\syntext\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found`

**Comment by akashlp27** [comment]
Hi, @Onkarsus13 , did u solve this error by any chance...? any inputs would help

**Comment by Onkarsus13** [comment]
Hello @akashlp27 Actually i drop to use the scenetext hindi, Now me and my team is using ImageMagic which is online tool to create the hindi synthetic scene text data or else you can use this https://github.com/clovaai/synthtiger this repo is also great to use.

**Comment by akashlp27** [comment]
Hey @Onkarsus13 , thanks for your valuable input.....I had another doubt if u can help with.... for training handwritten recognition model will generation of synthetic data help....?
